import type { APIRoute } from 'astro';
import { SITE, AUTHOR } from '../consts';
import { getPropositionContexts } from '../lib/collections';

/**
 * The Elementa, as a corpus a retrieval system can read.
 *
 * Separate from `/author.json` on purpose. That file is about a person and is
 * consulted when somebody asks about him; this is a textbook and is consulted
 * when somebody asks how attention works. Folding eighty-three propositions
 * into the author corpus would bury the profile it exists to surface — the
 * same dilution the Bibliotheca avoids by publishing one document per shelf
 * rather than one per book.
 *
 * Regenerated by `astro build`, which runs on every push to main including the
 * commits Sveltia makes from /admin. So writing a proposition publishes it to
 * the index with nothing to remember: the consumer re-fetches on its own
 * schedule and the new text is answerable within one cache window.
 *
 * Drafts are excluded because `getPropositionContexts` already excludes them
 * in production. A proposition in `review` is included: it is live on the site,
 * and a corpus that disagreed with the page about what exists would be worse
 * than one that includes work still being brought up to tier.
 */

/**
 * MDX down to prose.
 *
 * Mathematics is dropped rather than passed through. A dense-retrieval model
 * embeds `\frac{\partial L}{\partial w}` as tokens that mean nothing to it,
 * and leaving it in makes the passage *less* findable, not more — while the
 * reader who follows the citation gets the equation rendered properly on the
 * page it came from. The prose around an equation is what makes it findable.
 */
function toProse(mdx: string): string {
  return mdx
    // Frontmatter is already parsed; imports and exports are not content.
    .replace(/^---[\s\S]*?^---/m, '')
    .replace(/^\s*(import|export)\s.*$/gm, '')
    // Display and inline mathematics.
    .replace(/\$\$[\s\S]*?\$\$/g, ' ')
    .replace(/\$[^$\n]*\$/g, ' ')
    // Fenced code — a proposition's snippets are illustrations, not prose.
    .replace(/```[\s\S]*?```/g, ' ')
    // JSX components: drop the tags, keep any text between them.
    .replace(/<[A-Z][^>]*\/>/g, ' ')
    .replace(/<\/?[A-Za-z][^>]*>/g, ' ')
    // Markdown syntax that carries no meaning once flattened.
    .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[*_`>#]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export const GET: APIRoute = async () => {
  const props = await getPropositionContexts();

  const documents = props.map((c) => {
    const d = c.entry.data;
    const prose = toProse(c.entry.body ?? '');
    return {
      /* The citation everywhere else on the site: Book.Chapter.Proposition. */
      id: `elementa:${c.id}`,
      kind: 'proposition',
      /* The claim is the title. A proposition asserts one thing. */
      title: d.statement,
      url: new URL(
        `/elementa/${c.book.id}/${c.chapter.id.split('--')[1]}/${c.entry.id}`,
        SITE
      ).href,
      book: c.book.data.title,
      chapter: c.chapter.data.title,
      /* intuition | mechanics | research — how far past the textbook it sits. */
      level: d.level,
      updated: d.updated.toISOString().slice(0, 10),
      /**
       * Statement first, then the plain-language claim, then the prose. A
       * retrieval system reading only the opening still gets the assertion,
       * which is the part worth matching against a question.
       */
      text: [d.statement, d.claim, prose].filter(Boolean).join(' ').trim(),
    };
  })
  /* A proposition with nothing written under it cannot support a citation. */
  .filter((d) => d.text.length > 120);

  return new Response(
    JSON.stringify(
      {
        author: AUTHOR,
        site: SITE,
        work: 'Elementa',
        schema: 1,
        generated: new Date().toISOString(),
        documents,
      },
      null,
      2
    ),
    { headers: { 'Content-Type': 'application/json; charset=utf-8' } }
  );
};
